version: 1

system:
  interface: end0,eth0

sensor:
  enabled: True
  report_interval_seconds: 10
  sampling_interval_seconds: 5

mqtt:
  enabled: True
  host: localhost
  port: 1883

storage:
  enabled: True
  name: records.db

