version: 1

system:
  interface: end0,eth0
  static_ip: False
  address: 10.0.0.158
  netmask: 24
  gateway: 10.0.0.255
  dns: 8.8.8.8

sensor:
  enabled: True
  report_interval_seconds: 10
  sampling_interval_seconds: 5

mqtt:
  enabled: True
  host: localhost
  port: 1883

storage:
  enabled: True
  name: records.db

