---

- name: Install poetry for the current user
  ansible.builtin.shell: curl -sSL https://install.python-poetry.org | python3 -

# - name: Install poetry as root
#   become: yes
#   ansible.builtin.shell: curl -sSL https://install.python-poetry.org | python3 -

- name: Append poetry to bashrc for fiber user
  ansible.builtin.lineinfile:
      path: /home/fiber/.bashrc
      line: 'export PATH="$HOME/.local/bin:$PATH"'

- name: Append poetry to bashrc for root
  become: yes
  ansible.builtin.lineinfile:
      path: /root/.bashrc
      line: 'export PATH="/root/.local/bin:$PATH"'